ocr:
  ocr_url: "https://vision.api.cloud.yandex.net/vision/v1/batchAnalyze"
  jq_template: '[ .results[].results[].textDetection.pages[].blocks[].lines[].words[].text ] | join(" ")'
  ocr_languages:
    - "ru"
    - "en"
bot:
  commands:
    start: |
      Стартуем 😎
      Посмотри /help, чтобы узнать о работе с 🤖
    code: |
      Твой код отправлен админам
      Жди одобрения ⏳
    help: | 
      🔐 Отправь /code, чтобы получить доступ к боту
      💬 Для работы с чатом отправляй сообщение
      🖼️ Если есть фотка, с которой надо считать текст, то отправь мне её, а я вышлю текст
      ⚙️ /settings_help Посмотреть инструкцию к настройкам
    settings_help: |
      ⚙️ /settings - Показать настройки, которые применяются к каждому сообщению
      💬 /context <ваш контекст> - для задания контекста чата. 
      💬 /context_remove - для очистки контекста 
      📶 /freq_penalty - для задания частоты встречи токенов в тексте (Frequency penalty). Предел значений: [-2.0; 2.0]. По умолчанию 0
      🌡️ /temperature - для задания рандомности ответов. Предел значений: [0; 1]. По умолчанию 0.7
      📺 /stream - Включить/Отключить stream-mode. По умолчанию - выключено
      ⚙️ /settings_default - Установить настройки по умолчанию
  errors:
    completion: "Не смог получить ответ от chatGPT"
    sending: "Не смог отправить тебе ответ"
    converting: "Не смог обработать фотку"
    parsing: "Не смог распознать текст на фотке"
    context: "Не смог обработать ваш контекст"
    settings: "Не смог обработать ваши настройки"
